kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-gu30i
  namespace: sample_studio_project
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        tlsClientProfile: sample-tls-client-profile:1.0.0
        url: "'https://petstore.swagger.io/v2' & $pathAndQuery()"
        urlType: jsonata
        persistentConnections: false
        timeout: 30
        decompressResponse: true
        followRedirects: false
        chunkedUpload: false
