kind: MCPTools
apiVersion: api.ibm.com/v1
metadata:
  name: pet-tool-gu30i
  namespace: sample_studio_project
  version: "1.0"
  tags: []
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.


    Some useful links:

    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  labels:
    api-spec: ./pet-spec.yml
spec:
  tools:
    - name: update_pet
      description: This tool updates an existing pet in the Pet Store system. It
        modifies various pet attributes such as name, category, status, etc.
        Important parameters include the pet ID, name, category, photo URLs,
        tags, and status.
      inputSchema:
        type: object
        properties:
          id: &a1
            type: integer
            format: int64
            example: 10
            description: The unique identifier for the pet. Must be a 64-bit integer (e.g.,
              10).
          name: &a2
            type: string
            example: doggie
            description: The name of the pet (e.g., "doggie").
          category:
            type: object
            properties:
              id: &a3
                type: integer
                format: int64
                example: 1
              name: &a4
                type: string
                example: Dogs
            xml: &a5
              name: category
            description: The category of the pet, represented as an object.
          photoUrls:
            type: array
            xml: &a6
              wrapped: true
            items: &a7
              type: string
              xml:
                name: photoUrl
            description: An array of URLs to photos of the pet (e.g., ['url1', 'url2']).
              Required parameter.
          tags:
            type: array
            xml: &a8
              wrapped: true
            items:
              type: object
              properties:
                id: &a9
                  type: integer
                  format: int64
                name: &a10
                  type: string
              xml: &a11
                name: tag
            description: An array of tags for the pet (e.g., ['tag1', 'tag2']).
          status: &a12
            type: string
            description: The current status of the pet in the store. Can be available,
              pending, or sold (e.g., available).
            enum:
              - available
              - pending
              - sold
        required:
          - name
          - photoUrls
      title: Update an existing pet.
      x-api-binding:
        operationPath: /pet
        operationMethod: PUT
        api:
          $path: ./pet-spec.yml
    - name: add_pet
      description: This tool adds a new pet to the Pet Store system. It allows users
        to input a variety of pet details including ID, name, category, photo
        URLs, tags, and status.
      inputSchema:
        type: object
        properties:
          id: *a1
          name: *a2
          category:
            type: object
            properties:
              id: *a3
              name: *a4
            xml: *a5
            description: A nested object representing the pet's category.
          photoUrls:
            type: array
            xml: *a6
            items: *a7
            description: An array of URLs pointing to photos of the pet (e.g., ['url1',
              'url2']).
          tags:
            type: array
            xml: *a8
            items:
              type: object
              properties:
                id: *a9
                name: *a10
              xml: *a11
            description: An array of strings representing the pet's tags (e.g., ['tag1',
              'tag2']).
          status: *a12
        required:
          - name
          - photoUrls
      title: Add a new pet to the store.
      x-api-binding:
        operationPath: /pet
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: find_pets_by_status
      description: This tool retrieves pets from the Pet Store system based on their
        status. Users can input multiple status values separated by commas to
        retrieve pets in those specific statuses.
      inputSchema:
        type: object
        properties:
          status:
            description: The status to filter pets by. Can be available, pending, or sold
              (e.g., available).
            x-parameter-location: query
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
        required:
          - status
      title: Finds Pets by status.
      x-api-binding:
        operationPath: /pet/findByStatus
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: find_pets_by_tags
      description: This tool retrieves pets from the Pet Store system based on their
        tags. Users can input multiple tag values separated by commas to
        retrieve pets associated with those specific tags.
      inputSchema:
        type: object
        properties:
          tags:
            description: An array of strings representing the tags to filter pets by (e.g.,
              ['tag1', 'tag2']).
            x-parameter-location: query
            type: array
            items:
              type: string
        required:
          - tags
      title: Finds Pets by tags.
      x-api-binding:
        operationPath: /pet/findByTags
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: get_pet_by_id
      description: This tool retrieves a specific pet from the Pet Store system based
        on its ID. This is useful for viewing detailed pet information.
      inputSchema:
        type: object
        properties:
          petId:
            description: The unique identifier for the pet to fetch. Must be a 64-bit
              integer (e.g., 10).
            x-parameter-location: path
            type: integer
            format: int64
        required:
          - petId
      title: Find pet by ID.
      x-api-binding:
        operationPath: /pet/{petId}
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: update_pet_with_form
      description: This tool updates an existing pet in the Pet Store system based on
        form data. It accepts the pet ID, name, and status for updating.
      inputSchema:
        type: object
        properties:
          petId:
            description: The unique identifier for the pet, in integer format (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
          name:
            description: The name of the pet that needs to be updated.
            x-parameter-location: query
            type: string
          status:
            description: The current status of the pet (e.g., "available").
            x-parameter-location: query
            type: string
        required:
          - petId
      title: Updates a pet in the store with form data.
      x-api-binding:
        operationPath: /pet/{petId}
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: delete_pet
      description: This tool deletes a pet from the Pet Store system. It requires an
        API key and the pet ID for authentication and identification.
      inputSchema:
        type: object
        properties:
          api_key:
            description: The API key for authentication, according to the system's
              requirements.
            x-parameter-location: header
            type: string
          petId:
            description: The unique identifier for the pet, in integer format (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
        required:
          - petId
      title: Deletes a pet.
      x-api-binding:
        operationPath: /pet/{petId}
        operationMethod: DELETE
        api:
          $path: ./pet-spec.yml
    - name: upload_pet_image
      description: This tool enables the upload of an image for a specific pet in the
        Pet Store system. It accepts the pet ID, additional metadata, and the
        image file itself for the update.
      inputSchema:
        type: object
        properties:
          petId:
            description: The unique identifier for the pet, in integer format (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
          additionalMetadata:
            description: Additional metadata to associate with the uploaded file, in string
              format (e.g., "owner").
            x-parameter-location: query
            type: string
          body:
            type: string
            format: binary
            description: The binary content of the file to be uploaded, required.
        required:
          - petId
          - body
      title: Uploads an image.
      x-api-binding:
        operationPath: /pet/{petId}/uploadImage
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: get_pet_inventory
      description: This tool retrieves a map of status codes to quantities from the
        Pet Store system. It provides an overview of the pet store's inventory.
      inputSchema:
        type: object
        properties: {}
      title: Returns pet inventories by status.
      x-api-binding:
        operationPath: /store/inventory
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: place_pet_order
      description: This tool places a new order in the Pet Store system. It requires
        parameters such as ID, pet ID, quantity, ship date, status, and
        completion status.
      inputSchema:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 10
            description: The ID of the order (e.g., 10).
          petId:
            type: integer
            format: int64
            example: 198772
            description: The ID of the pet (e.g., 198772).
          quantity:
            type: integer
            format: int32
            example: 7
            description: The number of pets in the order (e.g., 7).
          shipDate:
            type: string
            format: date-time
            description: The planned delivery date and time (e.g., "2023-06-15T12:15:00Z").
          status:
            type: string
            description: The current status of the order, which can be 'placed', 'approved',
              or 'delivered' (e.g., 'approved').
            example: approved
            enum:
              - placed
              - approved
              - delivered
          complete:
            type: boolean
            description: A boolean flag indicating if the order is complete or not.
      title: Place an order for a pet.
      x-api-binding:
        operationPath: /store/order
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: get_order_by_id
      description: This tool retrieves a specific order by its ID from the Pet Store
        system. It is useful for viewing detailed order information and has
        specific ID value requirements for valid responses.
      inputSchema:
        type: object
        properties:
          orderId:
            description: The ID of the order that needs to be fetched (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
        required:
          - orderId
      title: Find purchase order by ID.
      x-api-binding:
        operationPath: /store/order/{orderId}
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: delete_pet_order
      description: This tool deletes a specific order from the Pet Store system by its
        ID. It has specific ID value requirements for valid responses and does
        not accept non-integer values.
      inputSchema:
        type: object
        properties:
          orderId:
            description: The ID of the order that needs to be deleted (e.g., 12345).
            x-parameter-location: path
            type: integer
            format: int64
        required:
          - orderId
      title: Delete purchase order by identifier.
      x-api-binding:
        operationPath: /store/order/{orderId}
        operationMethod: DELETE
        api:
          $path: ./pet-spec.yml
    - name: create_user
      description: This tool creates a new user in the Pet Store system. It requires
        inputs such as ID, username, first name, last name, email, password,
        phone, and user status.
      inputSchema:
        type: object
        properties:
          id: &a13
            type: integer
            format: int64
            example: 10
            description: The unique identifier for the user, provided as an integer (e.g.,
              10).
          username: &a14
            type: string
            example: theUser
            description: The new username for the user (e.g., "theUser").
          firstName: &a15
            type: string
            example: John
            description: The first name of the user, formatted as a string (e.g., "John").
          lastName: &a16
            type: string
            example: James
            description: The last name of the user, formatted as a string (e.g., "James").
          email: &a17
            type: string
            example: john@email.com
            description: The email address of the user, formatted as a string (e.g.,
              "john@email.com").
          password: &a18
            type: string
            example: "12345"
            description: The password for the user, formatted as a string (e.g., "12345").
          phone: &a19
            type: string
            example: "12345"
            description: The phone number of the user, formatted as a string (e.g.,
              "12345").
          userStatus: &a20
            type: integer
            description: The status of the user, provided as an integer (e.g., 1).
            format: int32
            example: 1
      title: Create user.
      x-api-binding:
        operationPath: /user
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: create_users_from_list
      description: This tool creates multiple users in the Pet Store system based on
        an input array. It simplifies the process of adding multiple users at
        once.
      inputSchema:
        type: object
        properties:
          body:
            type: array
            items:
              type: object
              properties:
                id: *a13
                username: *a14
                firstName: *a15
                lastName: *a16
                email: *a17
                password: *a18
                phone: *a19
                userStatus: *a20
              xml:
                name: user
            description: An array of users to be created. Each user should have the same
              fields as in createUser (id, username, firstName, lastName, email,
              password, phone, userStatus).
        required:
          - body
      title: Creates list of users with given input array.
      x-api-binding:
        operationPath: /user/createWithList
        operationMethod: POST
        api:
          $path: ./pet-spec.yml
    - name: log_in_user
      description: This tool logs the user into the Pet Store system. It requires a
        username and password for authentication purposes.
      inputSchema:
        type: object
        properties:
          username:
            description: The user name for login.
            x-parameter-location: query
            type: string
          password:
            description: The password for login in clear text. Do not include this in
              production code for security reasons.
            x-parameter-location: query
            type: string
      title: Logs user into the system.
      x-api-binding:
        operationPath: /user/login
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: log_out_user
      description: This tool logs the user out of the Pet Store system, providing a
        secure sign-off process.
      inputSchema:
        type: object
        properties: {}
      title: Logs out current logged in user session.
      x-api-binding:
        operationPath: /user/logout
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: get_user_by_name
      description: This tool retrieves a user's details from the Pet Store system
        based on the username. It is useful for viewing user information
        directly by username.
      inputSchema:
        type: object
        properties:
          username:
            description: The name that needs to be fetched. Use 'user1' for testing (e.g.,
              user1).
            x-parameter-location: path
            type: string
        required:
          - username
      title: Get user by user name.
      x-api-binding:
        operationPath: /user/{username}
        operationMethod: GET
        api:
          $path: ./pet-spec.yml
    - name: update_user
      description: This tool updates a specific user in the Pet Store system. It
        requires inputs such as username, ID, various user details, and user
        status, but can only be done by the logged-in user.
      inputSchema:
        type: object
        properties:
          username:
            description: The username to be updated. The value should match the existing
              username in the system (e.g., "theUser").
            x-parameter-location: path
            type: string
          id: *a13
          body_username: *a14
          firstName: *a15
          lastName: *a16
          email: *a17
          password: *a18
          phone: *a19
          userStatus: *a20
        required:
          - username
      title: Update user resource.
      x-api-binding:
        operationPath: /user/{username}
        operationMethod: PUT
        api:
          $path: ./pet-spec.yml
    - name: delete_user
      description: This tool deletes a specific user from the Pet Store system based
        on the username. It can only be done by the logged-in user for security
        reasons.
      inputSchema:
        type: object
        properties:
          username:
            description: The username of the user to be deleted. The value should match the
              existing username in the system (e.g., "theUser").
            x-parameter-location: path
            type: string
        required:
          - username
      title: Delete user resource.
      x-api-binding:
        operationPath: /user/{username}
        operationMethod: DELETE
        api:
          $path: ./pet-spec.yml
