kind: MCPTools
apiVersion: api.ibm.com/v1
metadata:
  name: test-external-server-tool-w0ak9
  namespace: test-project
  version: "1.0"
  tags: []
  description: test description
  domain: mcp
  labels: {}
spec:
  tools:
    - name: read_wiki_structure
      title: read_wiki_structure
      description: >-
        Get a list of documentation topics for a GitHub repository.


        Args:
            repoName: GitHub repository in owner/repo format (e.g. "facebook/react")
      inputSchema:
        properties:
          repoName:
            type: string
        required:
          - repoName
        type: object
    - name: read_wiki_contents
      title: read_wiki_contents
      description: >-
        View documentation about a GitHub repository.


        Args:
            repoName: GitHub repository in owner/repo format (e.g. "facebook/react")
      inputSchema:
        properties:
          repoName:
            type: string
        required:
          - repoName
        type: object
    - name: ask_question
      title: ask_question
      description: >-
        Ask any question about a GitHub repository and get an AI-powered,
        context-grounded response.


        Args:
            repoName: GitHub repository or list of repositories (max 10) in owner/repo format
            question: The question to ask about the repository
      inputSchema:
        properties:
          repoName:
            anyOf:
              - type: string
              - items:
                  type: string
                type: array
          question:
            type: string
        required:
          - repoName
          - question
        type: object
