kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: test-external-server-server-w0ak9
  namespace: test-project
  version: "1.0"
  tags: []
  domain: mcp
  labels:
    origin: mcp-mcp
spec:
  title: test-external-server
  protocolVersion: V2025_11_25
  quota:
    $ref: test-project:quota-w0ak9:1.0
  policy-sequence:
    - $ref: test-project:policy-sequence-w0ak9:1.0
  capabilities:
    tools:
      - $ref: test-project:test-external-server-tool-w0ak9:1.0
