---
kind: LLMProvider
apiVersion: api.ibm.com/v1
metadata:
  title: 'Watsonx Provider'
  name: watsonx-provider
  namespace: namespace-1
  version: '1.0'
  tags: []
  domain: ai-provider
  labels:
    gatewayTypes:
      - nano
spec:
  product:
    $ref: watsonx-ns:watsonx-conn-product:1.0
  provider:
    type: watsonx
    operations:
      - InvokeWatsonxModels
      - InvokeWatsonxTextGen
      - InvokeWatsonxTokenize
    apiKeySecret: watsonx-api-key
    tlsClientProfile: tls-client-profile-default:1.0.0
    projectId: project-id
    region: us-south
    opVersion: '2024-03-14'
---
kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-conn-api
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
spec:
  api-spec:
    $path: api-spec.json
  policy-sequence:
    - $ref: watsonx-ns:FreeFlowPolicySequence-5hJtu:1.0
---
kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-Gz8E3
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  namespace: client
  operation:
    subscription: {}
---
kind: Authorize
apiVersion: api.ibm.com/v1
metadata:
  name: Authorize-XwPMi
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  operation:
    subscription: {}
  namespace: client
---
kind: ExtractIdentity
apiVersion: api.ibm.com/v1
metadata:
  name: ExtractIdentity-hBK4W
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  credentialType:
    apiKey:
      clientId:
        httpHeader:
          name: X-IBM-Client-Id
      clientSecret:
        httpHeader:
          name: X-IBM-Client-Secret
  namespace: client
---
kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: FreeFlowPolicySequence-5hJtu
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: watsonx-ns:watsonx-provider:1.0
    - $ref: watsonx-ns:ExtractIdentity-hBK4W:1.0
    - $ref: watsonx-ns:Authenticate-Gz8E3:1.0
    - $ref: watsonx-ns:Authorize-XwPMi:1.0
    - $ref: watsonx-ns:IBMCloudLogin-def4T:1.0
    - $ref: watsonx-ns:Parse-ty5F8:1.0
    - $ref: watsonx-ns:OperationSwitch-qwEr2:1.0
  monitoring:
    $ref: watsonx-ns:Telemetry-iOygH:1.0
  error:
    - errorType: []
      execute:
        - $ref: watsonx-ns:Throw-BvG5K:1.0
---
kind: IBMCloudLogin
apiVersion: api.ibm.com/v1
metadata:
  name: IBMCloudLogin-def4T
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  apiKeySecret: watsonx-api-key
  tlsClientProfile: tls-client-profile-default:1.0.0
---
kind: InvokeWatsonxModels
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeWatsonxModels-1Fre2
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  inputMessage: request
  outputMessage: response
  region: $(watsonx-region)
  opVersion: $(watsonx-op-version)
  tlsClientProfile: $(watsonx-tls-client-profile)
  cachePolicy:
    cache:
      expire:
        static:
          seconds: 60
      scope:
        narrowScope: {}
      ignoreControlDirectives: true
---
kind: InvokeWatsonxTextGen
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeWatsonxTextGen-yU48r
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  inputMessage: request
  outputMessage: response
  region: $(watsonx-region)
  opVersion: $(watsonx-op-version)
  tlsClientProfile: $(watsonx-tls-client-profile)
  projectId: $(watsonx-project-id)
  cachePolicy:
    cache:
      expire:
        static:
          seconds: 60
      scope:
        narrowScope: {}
      ignoreControlDirectives: true
---
kind: InvokeWatsonxTokenize
apiVersion: api.ibm.com/v1
metadata:
  name: InvokeWatsonxTokenize-pQr3t
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  inputMessage: request
  outputMessage: response
  region: $(watsonx-region)
  opVersion: $(watsonx-op-version)
  tlsClientProfile: $(watsonx-tls-client-profile)
  projectId: $(watsonx-project-id)
  cachePolicy:
    cache:
      expire:
        static:
          seconds: 60
      scope:
        narrowScope: {}
      ignoreControlDirectives: true
---
kind: OperationSwitch
apiVersion: api.ibm.com/v1
metadata:
  name: OperationSwitch-qwEr2
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - conditions:
        - verbPath:
            path: /deployment-models
            verb: GET
      execute:
        - $ref: watsonx-ns:InvokeWatsonxModels-1Fre2:1.0
    - conditions:
        - verbPath:
            path: /text-generate
            verb: POST
      execute:
        - $ref: watsonx-ns:InvokeWatsonxTextGen-yU48r:1.0
    - conditions:
        - verbPath:
            path: /tokenize
            verb: POST
      execute:
        - $ref: watsonx-ns:InvokeWatsonxTokenize-pQr3t:1.0
---
kind: Parse
apiVersion: api.ibm.com/v1
metadata:
  name: Parse-ty5F8
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  documentType:
    json: {}
  input: request
---
kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-conn-plan
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  qos:
    withQuota:
      watsonx-token-weighted:
        - $ref: watsonx-ns:watsonx-token-weighted:1.0
      watsonx-default:
        - $ref: watsonx-ns:watsonx-default:1.0
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: watsonx-ns:watsonx-conn-api:1.0
            operations:
              - path: /deployment-models
                method: get
              - path: /text-generate
                method: post
              - path: /tokenize
                method: post
        telemetry: {}
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        apis:
          - $ref: watsonx-ns:watsonx-conn-api:1.0
            operations:
              - path: /deployment-models
                method: get
              - path: /text-generate
                method: post
              - path: /tokenize
                method: post
---
kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-conn-product
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  apis:
    - $ref: watsonx-ns:watsonx-conn-api:1.0
  plans:
    - $ref: watsonx-ns:watsonx-conn-plan:1.0
---
kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-token-weighted
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  maxRequest: 10000
  interval: 60s
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: $variable('aiGeneratedTokenCount')
        exceedAction: return429
        intervalOffset: 0
        dynamicValue: ''
---
kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-default
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  maxRequest: 100
  interval: 10s
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: '1'
        exceedAction: return429
        intervalOffset: 0
        dynamicValue: ''
---
kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: Telemetry-iOygH
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  verbosity:
    - level: basic
      onSuccessTrimTo: none
      inboundLevel: basic
      outboundLevel: basic
      operations:
        - path: /deployment-models
          method: GET
        - path: /text-generate
          method: POST
        - path: /tokenize
          method: POST
---
kind: Throw
apiVersion: api.ibm.com/v1
metadata:
  name: Throw-BvG5K
  namespace: watsonx-ns
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  error:
    CustomError:
      message: This is a custom error
      messageType: plain
      status: 429

