kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: openai-token-weighted-bjpi9
  namespace: TEST_LLM
  version: '1.0'
  tags: []
  description: ''
spec:
  maxRequest: 100
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: $variable('aiGeneratedTokenCount')
        exceedAction: continue
        intervalOffset: 0
        dynamicValue: ''
