kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: product-join_chatgpt-bjpi9
  namespace: TEST_LLM
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  apis:
    - $ref: TEST_LLM:api-join_chatgpt-bjpi9:1.0
  plans:
    - $ref: TEST_LLM:plan-join_chatgpt-bjpi9:1.0
