kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: sample_test_mcp-freeflowpolicysequence-gu30i
  namespace: SAMPLE_TEST_MCP
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: SAMPLE_TEST_MCP:invoke-gu30i:1.0
  monitoring:
    $ref: SAMPLE_TEST_MCP:telemetry-gu30i:1.0
