kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: policy-sequence-project-2
  namespace: test-project
  version: "1.0"
  tags: []
  domain: mcp
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: test-project:mcp-invoke-project-2:1.0
  monitoring:
    $ref: test-project:telemetry-project-2:1.0
