kind: ExtractIdentity
apiVersion: api.ibm.com/v1
metadata:
  name: ExtractIdentity-p2k4a
  namespace: DPNano_Product_LLM_Provider
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  credentialType:
    apiKey:
      clientId:
        httpHeader:
          name: X-IBM-Client-Id
      clientSecret:
        httpHeader:
          name: X-IBM-Client-Secret
  namespace: client
