kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: freeflowpolicysequence-watsonx-conn-sample-p2k4a
  namespace: DPNano_Product_LLM_Provider
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: DPNano_Product_LLM_Provider:ExtractIdentity-p2k4a:1.0
    - $ref: DPNano_Product_LLM_Provider:Authenticate-p2k4a:1.0
    - $ref: DPNano_Product_LLM_Provider:Authorize-p2k4a:1.0
    - $ref: DPNano_Product_LLM_Provider:my-rate-limit:1.0
    - $ref: DPNano_Product_LLM_Provider:IBMCloudLogin-p2k4a:1.0
    - $ref: DPNano_Product_LLM_Provider:Parse-p2k4a:1.0
    - $ref: DPNano_Product_LLM_Provider:OperationSwitch-p2k4a:1.0
  monitoring:
    $ref: DPNano_Product_LLM_Provider:Telemetry-p2k4a:1.0
