kind: IBMCloudLogin
apiVersion: api.ibm.com/v1
metadata:
  name: IBMCloudLogin-p2k4a
  namespace: DPNano_Product_LLM_Provider
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  apiKeySecret: placeholder-api-key
  tlsClientProfile: tls-client-profile-default:1.0.0
