kind: OperationSwitch
apiVersion: api.ibm.com/v1
metadata:
  name: OperationSwitch-p2k4a
  namespace: DPNano_Product_LLM_Provider
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  cases:
    - conditions:
        - verbPath:
            path: /deployment-models
            verb: GET
      execute:
        - $ref: DPNano_Product_LLM_Provider:InvokeWatsonxModels-p2k4a:1.0
    - conditions:
        - verbPath:
            path: /text-generate
            verb: POST
      execute:
        - $ref: DPNano_Product_LLM_Provider:InvokeWatsonxTextGen-p2k4a:1.0
    - conditions:
        - verbPath:
            path: /tokenize
            verb: POST
      execute:
        - $ref: DPNano_Product_LLM_Provider:InvokeWatsonxTokenize-p2k4a:1.0
